import { Category, Product } from "@/types";

export const initialCategories: Category[] = [
  {
    id: "cat-1",
    name: "Kolyeler",
    slug: "kolyeler",
    description: "Zarafeti boynunuzda taşıyın. Pırlanta, baget ve el işçiliği gümüş kolye koleksiyonu.",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=900&auto=format&fit=crop",
    orderIndex: 1,
  },
  {
    id: "cat-2",
    name: "Bileklikler",
    slug: "bileklikler",
    description: "Zarif su yolu bileklikler, şık kelepçeler ve minimal zincir tasarımları.",
    imageUrl: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=900&auto=format&fit=crop",
    orderIndex: 2,
  },
  {
    id: "cat-3",
    name: "Yüzükler",
    slug: "yuzukler",
    description: "Özel anlarınızı taçlandıran tektaş, tamtur ve sanatsal tasarım yüzükler.",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=900&auto=format&fit=crop",
    orderIndex: 3,
  },
  {
    id: "cat-4",
    name: "Küpeler",
    slug: "kupeler",
    description: "Işıltısıyla bakışları üzerinize çekecek altın kaplama ve inci küpeler.",
    imageUrl: "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=900&auto=format&fit=crop",
    orderIndex: 4,
  },
];

export const initialProducts: Product[] = [
  {
    id: "custom-helmet-1",
    title: "Pist & Yarış Kaskı Özel Tasarım Kolye (Two-Tone)",
    slug: "pist-yaris-kaski-kolye",
    description: "Usta ellerde şekillenen iki renkli pist yarış kaskı kolyesi. 925 ayar has gümüş gövde, altın yaldız kaplamalı vizör, çene yazısı ve arka ay-yıldız detayı. 55 cm masif küp zinciriyle birlikte özel kadife kutusunda teslim edilir.",
    price: 1890,
    salePrice: 1590,
    category: "kolyeler",
    images: [
      "/images/custom/helmet-racing.png",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 25,
    isFeatured: true,
    isNew: true,
    material: "925 Has Gümüş & Altın Yaldız Vizör",
    badge: "Atölye İmzası",
    rating: 5.0,
    reviewCount: 34,
    createdAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "custom-helmet-2",
    title: "Motocross Enduro Siperlikli Kask Kolye",
    slug: "motocross-enduro-kask-kolye",
    description: "Off-road ve motocross tutkunlarına özel siperlikli kask tasarımı. Masif gümüş gövde üzerine altın yıldız aplike ve özel fileli gözlük dokusu. Ömür boyu kararmaz cila garantilidir.",
    price: 1790,
    salePrice: 1490,
    category: "kolyeler",
    images: [
      "/images/custom/helmet-motocross.jpg",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 20,
    isFeatured: true,
    isNew: true,
    material: "925 Has Gümüş & Altın Yıldız Detay",
    badge: "Biker Özel",
    rating: 4.9,
    reviewCount: 22,
    createdAt: "2026-09-01T11:00:00Z",
  },
  {
    id: "custom-logo-3",
    title: "Honda Wing Kanat Lazer Kesim Masif Gümüş Kolye",
    slug: "honda-wing-kanat-kolye",
    description: "Hassas lazer kesim Honda Wing kanat amblemi ve masif yazı. Ayna parlaklığında rodyum kaplama kararmaz cila korumalı. Masif küp zincir hediyelidir.",
    price: 1550,
    salePrice: 1290,
    category: "kolyeler",
    images: [
      "/images/custom/logo-honda.png",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 30,
    isFeatured: true,
    isNew: true,
    material: "925 Ayar Has Gümüş (Ayna Parlaklığı)",
    badge: "Motorsport",
    rating: 5.0,
    reviewCount: 19,
    createdAt: "2026-09-01T12:00:00Z",
  },
  {
    id: "prod-1",
    title: "Aura Baget Pırlanta Görünümlü Gümüş Kolye",
    slug: "aura-baget-kolye",
    description: "Işıltısını asaletinden alan Aura Baget Kolye, 925 ayar gümüş üzerine 14 ayar altın mikron kaplama ile üretilmiştir. AAAA kalite pırlanta kesim zirkon taşların kusursuz dizilimiyle her anınıza eşsiz bir ışıltı katar. Antialerjiktir ve kararmaz koruyucu cila ile zırhlanmıştır.",
    price: 1850,
    salePrice: 1490,
    category: "kolyeler",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 14,
    isFeatured: true,
    isNew: true,
    material: "925 Ayar Gümüş / 14K Altın Kaplama",
    stone: "AAAA Kalite Pırlanta Kesim Zirkon",
    carat: "1.25 ct Eşdeğeri",
    weight: "3.45 gr",
    badge: "Çok Satan",
    rating: 4.9,
    reviewCount: 28,
    createdAt: "2026-08-15T10:00:00Z",
    reviews: [
      {
        id: "rev-1",
        productId: "prod-1",
        authorName: "Selin Yılmaz",
        rating: 5,
        comment: "Kutusunu açar açmaz büyülendim! Işıltısı fotoğraflardakinden bile daha güzel. Özel kadife kutusu ve garanti kartıyla geldi. Havale ile sipariş verdim ertesi gün elimdeydi.",
        date: "28 Ağustos 2026",
        isApproved: true,
        verifiedBuyer: true,
      },
      {
        id: "rev-2",
        productId: "prod-1",
        authorName: "Merve K.",
        rating: 5,
        comment: "Yaklaşık 3 haftadır boynumdan çıkarmıyorum, duşta bile denedim hiçbir kararma olmadı. Cila kalitesi gerçekten dedikleri gibi birinci sınıf.",
        date: "22 Ağustos 2026",
        isApproved: true,
        verifiedBuyer: true,
      },
    ],
  },
  {
    id: "prod-2",
    title: "Venedik Su Yolu Kristal Bileklik",
    slug: "venedik-su-yolu-bileklik",
    description: "Zarafetin zamansız simgesi su yolu bileklik, el mıhlaması berrak taşlarıyla bileğinizde akıcı bir zarafet sergiler. Çift güvenlik kilit mekanizması sayesinde güvenle taşınır.",
    price: 2450,
    salePrice: 1980,
    category: "bileklikler",
    images: [
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 8,
    isFeatured: true,
    isNew: false,
    material: "925 Ayar Has Gümüş",
    stone: "Pırlanta Kesim Zirkon",
    carat: "3.50 ct",
    weight: "7.80 gr",
    badge: "Fırsat",
    rating: 4.8,
    reviewCount: 19,
    createdAt: "2026-08-10T12:00:00Z",
    reviews: [
      {
        id: "rev-3",
        productId: "prod-2",
        authorName: "Büşra D.",
        rating: 5,
        comment: "Nişanım için aldım, herkes gerçek pırlanta sandı. Kilit kısmı çok sağlam, güven veriyor.",
        date: "19 Ağustos 2026",
        isApproved: true,
        verifiedBuyer: true,
      },
    ],
  },
  {
    id: "prod-3",
    title: "Soleil 14K Altın Kaplama Madalyon Kolye",
    slug: "soleil-madalyon-kolye",
    description: "Güneşin hayat veren enerjisinden ilhamla tasarlanan Soleil madalyon kolye, vintage dokusu ve kabartmalı rölyef işçiliği ile bohem lüksün en seçkin örneğidir.",
    price: 1650,
    category: "kolyeler",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 19,
    isFeatured: true,
    isNew: true,
    material: "14K Sarı Altın Mikron Kaplama",
    stone: "Merkezde Doğal Sitrin Taşı",
    weight: "5.10 gr",
    badge: "Yeni",
    rating: 5.0,
    reviewCount: 12,
    createdAt: "2026-08-20T14:30:00Z",
    reviews: [
      {
        id: "rev-4",
        productId: "prod-3",
        authorName: "Aslıhan T.",
        rating: 5,
        comment: "Zincir boyu tam göğüs hizasında çok şık duruyor. Madalyonun ağırlığı ve detayı çok kaliteli hissettiriyor.",
        date: "25 Ağustos 2026",
        isApproved: true,
        verifiedBuyer: true,
      }
    ],
  },
  {
    id: "prod-4",
    title: "Eternity Baget Tamtur Zarafet Yüzüğü",
    slug: "eternity-baget-tamtur-yuzuk",
    description: "Sonsuz sevginin ve bağlılığın en asil ifadesi. 360 derece kesintisiz dizilmiş baget taşlar, prizmatik ışık kırılmalarıyla her hareketinizde parıldar.",
    price: 1950,
    salePrice: 1590,
    category: "yuzukler",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 12,
    isFeatured: true,
    isNew: false,
    material: "925 Ayar Rodyum Kaplama Gümüş",
    stone: "Baget Zirkon",
    carat: "2.10 ct",
    weight: "3.90 gr",
    badge: "Çok Satan",
    rating: 4.9,
    reviewCount: 34,
    createdAt: "2026-08-05T09:15:00Z",
    reviews: [
      {
        id: "rev-5",
        productId: "prod-4",
        authorName: "Zeynep Ç.",
        rating: 5,
        comment: "Parmaktaki duruşu inanılmaz zarif. Numara tam oldu, hediye paketi çok özenliydi.",
        date: "14 Ağustos 2026",
        isApproved: true,
        verifiedBuyer: true,
      }
    ],
  },
  {
    id: "prod-5",
    title: "Luna Damla Doğal Barok İnci Küpe",
    slug: "luna-damla-barok-inci-kupe",
    description: "Her biri denizlerin derinliklerinden gelen benzersiz formdaki gerçek tatlı su barok incileri. Doğanın kusursuz benzersizliğini kulaklarınızda taşıyın.",
    price: 1400,
    salePrice: 1190,
    category: "kupeler",
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 6,
    isFeatured: false,
    isNew: true,
    material: "14K Altın Kaplama Gümüş Klips",
    stone: "Doğal Tatlı Su İncisi (Barok)",
    weight: "4.80 gr (Çift)",
    rating: 4.7,
    reviewCount: 9,
    createdAt: "2026-08-18T16:00:00Z",
    reviews: [],
  },
  {
    id: "prod-6",
    title: "Hera Sarmal Minimal Kelepçe Bileklik",
    slug: "hera-sarmal-kelepce-bileklik",
    description: "Antik Yunan estetiğini modern İtalyan formuyla birleştiren Hera kelepçe. Esnek yapısıyla bileğe kusursuz uyum sağlar, tek başına veya saat yanında harika görünür.",
    price: 2100,
    category: "bileklikler",
    images: [
      "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 11,
    isFeatured: false,
    isNew: false,
    material: "925 Ayar Gümüş / 18K Rose Gold Kaplama",
    stone: "Uçlarda Mikro Pavé Taşlar",
    weight: "8.50 gr",
    rating: 4.9,
    reviewCount: 16,
    createdAt: "2026-07-28T11:00:00Z",
    reviews: [],
  },
  {
    id: "prod-7",
    title: "Celeste Safir Işıltılı Vintage Kolye",
    slug: "celeste-safir-vintage-kolye",
    description: "Derin gece mavisi safir rengi kristalin etrafını saran mikro pırlanta ışıltısı. Kraliyet mücevherlerinin ağırbaşlı zarafetini taşır.",
    price: 2250,
    salePrice: 1890,
    category: "kolyeler",
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 7,
    isFeatured: true,
    isNew: true,
    material: "925 Ayar Gümüş",
    stone: "Laboratuvar Üretimi Safir & Zirkon",
    weight: "4.10 gr",
    badge: "Özel Tasarım",
    rating: 5.0,
    reviewCount: 8,
    createdAt: "2026-08-26T18:00:00Z",
    reviews: [],
  },
  {
    id: "prod-8",
    title: "Daphne Halka Baget Taşlı Küpe",
    slug: "daphne-halka-baget-kupe",
    description: "Günlük hayatta konfor, gece davetlerinde göz kamaştırıcı ışıltı. İçi ve dışı taşlarla bezeli inovatif halka kilit mekanizması.",
    price: 1550,
    category: "kupeler",
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop",
    ],
    stock: 15,
    isFeatured: false,
    isNew: false,
    material: "14K Altın Kaplama Gümüş",
    stone: "Baget Kesim Zirkon",
    weight: "3.80 gr",
    rating: 4.8,
    reviewCount: 14,
    createdAt: "2026-08-11T13:40:00Z",
    reviews: [],
  },
];
